version: '3'
services:
  eureka-server:
    build: ./EurekaServer
    image: spring-cloud/eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - broker

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT= 2181
      - ZOOKEEPER_TICK_TIME= 2000
    ports:
      - "22181:2181"

  broker:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME= broker
      - KAFKA_BROKER_ID= 1
      - KAFKA_ZOOKEEPER_CONNECT= zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS= PLAINTEXT://localhost:9092,PLAINTEXT_HOST://broker:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP= PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME= PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR= 1

  redis1:
    image: redis
    container_name: redis1
    ports:
      - "6379:6379"
  redis2:
    image: redis
    container_name: redis2
    ports:
      - "6380:6379"
  redis3:
    image: redis
    container_name: redis3
    ports:
      - "6381:6379"
  redis4:
    image: redis
    container_name: redis4
    ports:
      - "6382:6379"

  load-balancer:
    build: ./LoadBalancer
    image: load-balancer
    container_name: load-balancer
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
    ports:
      - "9000:9000"
    depends_on:
      - eureka-server
    links:
      - eureka-server

  node1:
    build: ./Node
    container_name: node1
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
      - NODE_ID=1
      - NODE_NAME=Node1
      - NODE_PORT=8081
      - REDIS_HOST=redis1
    volumes:
      - ./Storage/Node1:/app/Storage/Node1
      - ./Storage/Node1/Users:/app/Storage/Node1/Users
    ports:
      - "8081:8080"
    depends_on:
      - eureka-server
    links:
      - eureka-server

  node2:
    build: ./Node
    container_name: node2
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
      - NODE_ID=2
      - NODE_NAME=Node2
      - NODE_PORT=8082
      - REDIS_HOST=redis2
    volumes:
      - ./Storage/Node2:/app/Storage/Node2
      - ./Storage/Node2/Users:/app/Storage/Node2/Users
    ports:
      - "8082:8080"
    depends_on:
      - eureka-server
    links:
      - eureka-server

  node3:
    build: ./Node
    container_name: node3
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
      - NODE_ID=3
      - NODE_NAME=Node3
      - NODE_PORT=8083
      - REDIS_HOST=redis3
    volumes:
      - ./Storage/Node3:/app/Storage/Node3
      - ./Storage/Node3/Users:/app/Storage/Node3/Users
    ports:
      - "8083:8080"
    depends_on:
      - eureka-server
    links:
      - eureka-server

  node4:
    build: ./Node
    container_name: node4
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
      - NODE_ID=4
      - NODE_NAME=Node4
      - NODE_PORT=8084
      - REDIS_HOST=redis4
    volumes:
      - ./Storage/Node4:/app/Storage/Node4
      - ./Storage/Node4/Users:/app/Storage/Node4/Users
    ports:
      - "8084:8080"
    depends_on:
      - eureka-server
    links:
      - eureka-server