version: '3'
services:
  eureka-server:
    build: ./EurekaServer
    image: spring-cloud/eureka
    container_name: eureka-server
    ports:
      - "8761:8761"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT= 2181
      - ZOOKEEPER_TICK_TIME= 2000
    ports:
      - "22181:2181"

  broker:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID= 1
      - KAFKA_ZOOKEEPER_CONNECT= zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS= PLAINTEXT://localhost:9092,PLAINTEXT_HOST://broker:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP= PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME= PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR= 1

  load-balancer:
    build: ./LoadBalancer
    image: load-balancer
    container_name: load-balancer
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
    ports:
      - "9000:9000"
    depends_on:
      - eureka-server
    links:
      - eureka-server

  node1:
    build: ./Node
    container_name: node1
    environment:
#      - server.servlet.context-path=/Node1
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
      - NODE_ID=1
      - NODE_NAME=Node1
      - NODE_PORT=8081
    volumes:
      - ./Storage/Node1:/app/Storage/Node1
      - ./Storage/Node1/Users:/app/Storage/Node1/Users
    ports:
      - "8081:8080"
    depends_on:
      - eureka-server
      - broker
    links:
      - eureka-server

  node2:
    build: ./Node
    container_name: node2
    environment:
#      - server.servlet.context-path=/Node2
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
      - NODE_ID=2
      - NODE_NAME=Node2
      - NODE_PORT=8082
    volumes:
      - ./Storage/Node2:/app/Storage/Node2
      - ./Storage/Node2/Users:/app/Storage/Node2/Users
    ports:
      - "8082:8080"
    depends_on:
      - eureka-server
      - broker
    links:
      - eureka-server
#
#  node3:
#    build: ./Node
#    container_name: node3
#    environment:
##      - server.servlet.context-path=/Node3
#      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
#      - NODE_ID=3
#      - NODE_NAME=Node3
#      - NODE_PORT=8083
#    volumes:
#      - ./Storage/Node3:/app/Storage/Node3
#      - ./Storage/Node3/Users:/app/Storage/Node3/Users
#    ports:
#      - "8083:8080"
#    depends_on:
#      - eureka-server
#    links:
#      - eureka-server
#
#
#  node4:
#    build: ./Node
#    container_name: node4
#    environment:
##      - server.servlet.context-path=/Node4
#      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
#      - NODE_ID=4
#      - NODE_NAME=Node4
#      - NODE_PORT=8084
#    volumes:
#      - ./Storage/Node4:/app/Storage/Node4
#      - ./Storage/Node4/Users:/app/Storage/Node4/Users
#    ports:
#      - "8084:8080"
#    depends_on:
#      - eureka-server
#    links:
#      - eureka-server

