version: '3'
services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ID: 1
    environment:
      - NODE_ID=1
      - NODE_NAME=Node1
    volumes:
      - ./Storage/Node1:/app/Storage/Node1
      - ./Storage/Node1/Users:/app/Storage/Node1/Users
    ports:
      - "8081:8080"

  node2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ID: 2
    environment:
      - NODE_ID=2
      - NODE_NAME=Node2
    volumes:
      - ./Storage/Node2:/app/Storage/Node2
      - ./Storage/Node2/Users:/app/Storage/Node2/Users
    ports:
      - "8082:8080"

  node3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ID: 3
    environment:
      - NODE_ID=3
      - NODE_NAME=Node3
    volumes:
      - ./Storage/Node3:/app/Storage/Node3
      - ./Storage/Node3/Users:/app/Storage/Node3/Users
    ports:
      - "8083:8080"

  node4:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ID: 4
    environment:
      - NODE_ID=4
      - NODE_NAME=Node4
    volumes:
      - ./Storage/Node4:/app/Storage/Node4
      - ./Storage/Node4/Users:/app/Storage/Node4/Users
    ports:
      - "8084:8080"
